"""Host Audit — Configuration Drift (ADR-0009 §1, #124).

Observable behaviour only:
- a real ``ansible.posix.json`` --check --diff callback document (tests/fixtures/host_audit_drift,
  generated by running a check-mode playbook against local hosts) becomes per-host SPEC-ID rows;
- rows never carry diff text or no_log content, only paths, line counts and attribute names;
- Raw Provisioning Path hosts and hosts the audit could not inspect are not inspectable with a reason;
- a sub-run that fails as a whole makes only its part of the section not inspectable;
- the report model and template carry the section with a hand-written judgement column.
"""
import copy
import json
import sys
from pathlib import Path

import pytest
import yaml

ROOT_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT_DIR / "filter_plugins"))

from host_audit import host_audit_report_model  # noqa: E402
from host_audit_drift import (  # noqa: E402
    REASON_NOT_COLLECTED,
    REASON_RAW,
    host_audit_drift_parse,
    host_audit_drift_plan,
    host_audit_drift_section,
    summarize_diff,
)

FIXTURE = ROOT_DIR / "tests" / "fixtures" / "host_audit_drift" / "check_callback.json"
PLAYS = ["Fixture play"]
# Diff text present in the fixture's before/after; it must never reach a row.
DIFF_TEXT = ("new line", "added", "x=1", "y=2", "OLDSECRET", "NEWSECRET")


def _fixture_text():
    return FIXTURE.read_text(encoding="utf-8")


def _record(host, status="ok", release=""):
    return {"inventory_hostname": host, "status": status,
            "os": {"id": "rocky", "version_id": "9.4", "redhat_release": release} if status == "ok" else None}


# --- parse ---------------------------------------------------------------------------------------

def test_parse_real_callback_makes_spec_rows_per_host():
    parsed = host_audit_drift_parse(_fixture_text(), ["hosta", "hostb", "hostc"], PLAYS)
    assert parsed["status"] == "ok"
    hosta = parsed["hosts"]["hosta"]
    assert hosta["status"] == "ok"
    assert [r["spec_id"] for r in hosta["rows"]] == ["FIX-001", "FIX-003", "FIX-004", ""]
    assert hosta["rows"][0]["task"] == "Template a config (changed with diff)"
    assert hosta["rows"][3]["task"] == "Unlabelled task changes"


def test_parse_compliant_and_skipped_tasks_are_not_drift():
    parsed = host_audit_drift_parse(_fixture_text(), ["hosta"], PLAYS)
    ids = {r["spec_id"] for r in parsed["hosts"]["hosta"]["rows"]}
    assert "FIX-002" not in ids  # already compliant
    assert "FIX-005" not in ids  # skipped in check mode


def test_parse_never_copies_diff_text_or_no_log_content():
    parsed = host_audit_drift_parse(_fixture_text(), ["hosta", "hostb"], PLAYS)
    blob = json.dumps(parsed, ensure_ascii=False)
    for text in DIFF_TEXT:
        assert text not in blob
    secret_row = next(r for r in parsed["hosts"]["hosta"]["rows"] if r["spec_id"] == "FIX-003")
    assert "no_log" in secret_row["summary"]


def test_parse_summary_has_path_and_line_counts():
    parsed = host_audit_drift_parse(_fixture_text(), ["hosta"], PLAYS)
    rows = {r["spec_id"]: r for r in parsed["hosts"]["hosta"]["rows"]}
    assert rows["FIX-001"]["summary"] == "/srv/drift-fixture/t/conf.txt · +2/-1줄"
    assert "반복 2/3건 변경" in rows["FIX-004"]["summary"]
    assert "속성: state" in rows[""]["summary"]


def test_parse_failed_and_unreachable_hosts_are_not_inspectable():
    parsed = host_audit_drift_parse(_fixture_text(), ["hosta", "hostb", "hostc"], PLAYS)
    assert parsed["hosts"]["hostb"]["status"] == "failed"
    assert "FIX-006" in parsed["hosts"]["hostb"]["reason"]
    assert parsed["hosts"]["hostc"]["status"] == "unreachable"
    assert "Connection timed out" in parsed["hosts"]["hostc"]["reason"]


def test_parse_only_declared_plays_make_rows_but_failures_count_everywhere():
    doc = json.loads(_fixture_text())
    resolve = copy.deepcopy(doc["plays"][0])
    resolve["play"]["name"] = "Controller Pre-flight & Dynamic OpenBao Credential Resolution"
    resolve["tasks"] = [{"task": {"name": "Write temp key", "path": "/x/resolve_connection.yml:9"},
                         "hosts": {"hosta": {"changed": True, "action": "ansible.builtin.copy"},
                                   "hostd": {"failed": True, "msg": "OpenBao 조회 실패"}}}]
    doc["plays"].insert(0, resolve)
    parsed = host_audit_drift_parse(json.dumps(doc), ["hosta", "hostd"], PLAYS)
    assert "Write temp key" not in [r["task"] for r in parsed["hosts"]["hosta"]["rows"]]
    assert parsed["hosts"]["hostd"]["status"] == "failed"


def test_parse_skips_handlers():
    doc = json.loads(_fixture_text())
    doc["plays"][0]["tasks"].append({"task": {"name": "common : Restart chronyd", "path": "/r/roles/common/handlers/main.yml:2"},
                                     "hosts": {"hosta": {"changed": True}}})
    parsed = host_audit_drift_parse(json.dumps(doc), ["hosta"], PLAYS)
    assert "Restart chronyd" not in [r["task"] for r in parsed["hosts"]["hosta"]["rows"]]


def test_parse_strips_role_prefix_and_reads_multi_part_spec_ids():
    doc = {"plays": [{"play": {"name": "Fixture play"}, "tasks": [
        {"task": {"name": "docker_engine : [DOC-004-CACHE] Refresh cache", "path": "/r/roles/docker_engine/tasks/main.yml:66"},
         "hosts": {"hosta": {"changed": True}}}]}]}
    row = host_audit_drift_parse(doc, ["hosta"], PLAYS)["hosts"]["hosta"]["rows"][0]
    assert (row["spec_id"], row["task"]) == ("DOC-004-CACHE", "Refresh cache")


def test_parse_ignore_rules_move_noise_aside_with_reason():
    ignore = [{"spec_id": "FIX-004", "reason": "check 모드에서 항상 changed"}, {"task": "Unlabelled task changes", "reason": "r"}]
    hosta = host_audit_drift_parse(_fixture_text(), ["hosta"], PLAYS, ignore)["hosts"]["hosta"]
    assert [r["spec_id"] for r in hosta["rows"]] == ["FIX-001", "FIX-003"]
    assert [(r["spec_id"], r["reason"]) for r in hosta["excluded"]] == [("FIX-004", "check 모드에서 항상 changed"), ("", "r")]


def test_parse_tolerates_surrounding_text_and_flags_garbage():
    text = "[WARNING]: something {odd}\n" + _fixture_text() + "\nPLAYBOOK RECAP ***\nPlaybook run took 0 days\n"
    assert host_audit_drift_parse(text, ["hosta"], PLAYS)["status"] == "ok"
    for bad in ("", "ERROR! the playbook could not be found", "{not json"):
        result = host_audit_drift_parse(bad, ["hosta"], PLAYS)
        assert result["status"] == "error" and result["reason"]


def test_parse_host_missing_from_result_is_no_result():
    parsed = host_audit_drift_parse(_fixture_text(), ["hosta", "ghost"], PLAYS)
    assert parsed["hosts"]["ghost"]["status"] == "no_result"


def test_summarize_template_to_missing_file_hides_controller_temp_path():
    # Real shape of SEC-012 under --check when /etc/audit/rules.d/overseer.rules is absent.
    result = {"changed": True, "diff": [{"after": "-w /etc/passwd\n-w /etc/shadow\n",
                                         "after_header": "/home/u/.ansible/tmp/ansible-local-1abc/tmpx/audit.rules.j2",
                                         "before": ""}]}
    assert summarize_diff(result) == "새 파일(템플릿 audit.rules.j2) · +2/-0줄"


def test_summarize_prepared_diff_and_empty():
    assert summarize_diff({"changed": True, "diff": {"prepared": "+pkg-1.0"}}) == "변경 예정(모듈 요약)"
    assert summarize_diff({"changed": True}) == "변경 예정(diff 없음)"


# --- plan ----------------------------------------------------------------------------------------

def test_plan_routes_hosts_and_excludes_raw_and_uninspected():
    records = [
        _record("web1"),
        _record("lb1"),
        _record("c7", release="CentOS Linux release 7.9.2009 (Core)"),
        _record("c6", release="CentOS release 6.10 (Final)"),
        _record("down", status="unreachable"),
        _record("forced", release=""),
    ]
    plan = host_audit_drift_plan(
        records,
        site_scope=["web1", "lb1", "c7", "c6", "down", "forced"],
        agents_scope=["web1", "c7"],
        raw_declared={"forced": True, "c7": ""},
    )
    assert plan["site"] == ["lb1", "web1"]
    assert plan["agents"] == ["web1"]
    assert plan["excluded"] == {"c6": REASON_RAW, "c7": REASON_RAW, "forced": REASON_RAW, "down": REASON_NOT_COLLECTED}


def test_plan_explicit_false_overrides_detection():
    plan = host_audit_drift_plan([_record("c7", release="CentOS Linux release 7.9.2009 (Core)")],
                                 ["c7"], [], {"c7": False})
    assert plan["site"] == ["c7"]


# --- section -------------------------------------------------------------------------------------

def _section(agents_run=None):
    records = [_record(h) for h in ("hosta", "hostb", "hostc")] + [_record("c7", release="CentOS Linux release 7.9.2009 (Core)")]
    plan = host_audit_drift_plan(records, ["hosta", "hostb", "hostc", "c7"], ["hosta"], {})
    runs = {"site": {"ran": True, "rc": 4, "parsed": host_audit_drift_parse(_fixture_text(), plan["site"], PLAYS,
                                                                            [{"spec_id": "FIX-004", "reason": "노이즈"}])}}
    if agents_run is not None:
        runs["agents"] = agents_run
    return host_audit_drift_section(plan, runs)


def test_section_rows_counts_and_unavailable():
    section = _section({"ran": True, "rc": 0, "parsed": host_audit_drift_parse(_fixture_text(), ["hosta"], PLAYS)})
    site, agents = section["subruns"]
    assert (site["status"], site["hosts"], site["changed_hosts"]) == ("ok", 3, 2)
    assert agents["status"] == "ok"
    assert section["hosts_with_drift"] == 2
    assert section["excluded"] == [{"spec_id": "FIX-004", "task": "Looped lines", "reason": "노이즈", "hosts": 2}]
    reasons = {(u["host"], u["label"]) for u in section["unavailable"]}
    assert ("hostb", "점검불가(점검 중 오류)") in reasons
    assert ("hostc", "점검불가(접속 실패)") in reasons
    assert ("c7", "점검불가") in reasons
    assert section["by_host"]["c7"]["unavailable"][0]["reason"] == REASON_RAW


def test_section_failed_subrun_marks_only_that_part():
    section = _section({"ran": False, "rc": 124, "error": "시간 초과(3600초)", "parsed": {}})
    site, agents = section["subruns"]
    assert site["status"] == "ok" and site["rows"] > 0
    assert (agents["status"], agents["reason"]) == ("error", "시간 초과(3600초)")
    assert any(u["item"] == "Configuration Drift — Host Agents Config" for u in section["unavailable"])


def test_section_without_targets_is_skipped():
    section = host_audit_drift_section({"site": [], "agents": [], "excluded": {}}, {})
    assert [s["status"] for s in section["subruns"]] == ["skipped", "skipped"]


# --- report model / template ---------------------------------------------------------------------

def _model(section):
    records = [dict(_record("hosta"), schema_version=2, identity={"hostname": "hosta", "fqdn": "", "ips": [], "account": "audit"})]
    meta = {"run_id": "ha-1", "run_kind": "on_demand", "started_at": "2026-10-08T00:00:00Z",
            "generated_at": "2026-10-08T00:10:00Z", "targets": ["hosta"], "configuration_drift": section}
    return host_audit_report_model(records, meta)


def test_report_model_carries_drift_and_its_unavailable_entries():
    section = _section({"ran": False, "rc": 124, "error": "시간 초과", "parsed": {}})
    model = _model(section)
    assert model["configuration_drift"]["title"] == "Configuration Drift"
    assert any(c.startswith("Configuration Drift") for c in model["cover"]["contents"])
    assert any(u["item"].startswith("Configuration Drift") for u in model["unavailable"])


def test_report_model_without_drift_has_none():
    assert _model({})["configuration_drift"] is None


def test_template_renders_judgement_column_and_no_diff_text():
    jinja2 = pytest.importorskip("jinja2")
    env = jinja2.Environment(loader=jinja2.FileSystemLoader(str(ROOT_DIR / "roles" / "host_audit" / "templates")),
                             extensions=["jinja2.ext.do"])
    section = _section({"ran": True, "rc": 0, "parsed": host_audit_drift_parse(_fixture_text(), ["hosta"], PLAYS)})
    html = env.get_template("sections/configuration_drift.html.j2").render(m={"configuration_drift": section})
    assert "판단(수기)" in html
    assert "FIX-001" in html and "제외(check 모드 노이즈)" in html
    for text in DIFF_TEXT:
        assert text not in html
    appendix = env.get_template("sections/appendix_configuration_drift.html.j2").render(
        m={"configuration_drift": section}, host="c7")
    assert "Raw Provisioning Path" in appendix


# --- wiring --------------------------------------------------------------------------------------

def test_subrun_task_hides_credentials_and_cleans_up_raw_output():
    tasks = yaml.safe_load((ROOT_DIR / "roles" / "host_audit" / "tasks" / "drift_subrun.yml").read_text(encoding="utf-8"))
    block = tasks[0]
    run = next(t for t in block["block"] if "ansible.builtin.shell" in t)
    assert run["no_log"] is True
    assert "VAULT_SECRET_ID" in run["environment"]
    assert "VAULT_SECRET_ID" not in run["ansible.builtin.shell"]
    assert "--check --diff" in run["ansible.builtin.shell"]
    assert run["environment"]["ANSIBLE_STDOUT_CALLBACK"] == "ansible.posix.json"
    cleanup = block["always"][0]
    assert cleanup["ansible.builtin.file"]["state"] == "absent"


def test_declared_play_names_match_the_playbooks():
    tasks = yaml.safe_load((ROOT_DIR / "roles" / "host_audit" / "tasks" / "drift.yml").read_text(encoding="utf-8"))
    subruns = next(t for t in tasks if "_host_audit_drift_subruns" in (t.get("ansible.builtin.set_fact") or {}))
    for sub in subruns["ansible.builtin.set_fact"]["_host_audit_drift_subruns"]:
        plays = yaml.safe_load((ROOT_DIR / "playbooks" / sub["playbook"]).read_text(encoding="utf-8"))
        names = {p.get("name") for p in plays}
        assert set(sub["plays"]) <= names, sub["playbook"]


# --- Audit Baseline participation (#125) ---------------------------------------------------------

def test_baseline_findings_use_stable_ids_and_only_fully_judged_hosts():
    section = _section({"ran": True, "rc": 0, "parsed": host_audit_drift_parse(_fixture_text(), ["hosta"], PLAYS)})
    bf = section["baseline_findings"]
    # hostb failed mid-run, hostc unreachable, c7 is Raw path: none of them may turn Drift into 해소.
    assert bf["hosts"] == ["hosta"]
    ids = {f["id"] for f in bf["findings"]}
    assert {"site:FIX-001", "site:FIX-003", "agents:FIX-001", "site:task:Unlabelled task changes"} <= ids
    assert "site:FIX-004" not in ids  # excluded as noise


def test_baseline_findings_skip_hosts_of_a_failed_subrun():
    section = _section({"ran": False, "rc": 124, "error": "시간 초과", "parsed": {}})
    assert "hosta" not in section["baseline_findings"]["hosts"]


def test_baseline_compare_marks_drift_rows():
    from host_audit_baseline import host_audit_baseline_compare, host_audit_findings_index
    section = _section({"ran": True, "rc": 0, "parsed": host_audit_drift_parse(_fixture_text(), ["hosta"], PLAYS)})
    index = host_audit_findings_index({"configuration_drift": section})
    baseline = {"sections": {"configuration_drift": {"hosts": ["hosta"], "ids": {"hosta": ["site:FIX-001", "site:SEC-999"]}}}}
    out = host_audit_baseline_compare(index, baseline, [], {"started_at": "2026-10-08T00:00:00Z", "run_id": "r2"})
    assert out["status"]["configuration_drift|hosta|site:FIX-001"] == "지속"
    assert out["status"]["configuration_drift|hosta|site:FIX-003"] == "신규"
    assert out["resolved"] == ["configuration_drift|hosta|site:SEC-999"]
