import pytest
import yaml
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parent.parent

def test_requirements_includes_cisco_ios():
    """Verify requirements.yml defines cisco.ios collection"""
    req_file = ROOT_DIR / "requirements.yml"
    assert req_file.exists(), "requirements.yml is missing"
    with open(req_file, "r", encoding="utf-8") as f:
        req_data = yaml.safe_load(f)
    collections = [col.get("name") for col in req_data.get("collections", []) if isinstance(col, dict)]
    assert "cisco.ios" in collections, "cisco.ios collection missing in requirements.yml"

def test_cisco_backup_role_structure():
    """Verify roles/cisco_backup structure and required files"""
    role_dir = ROOT_DIR / "roles" / "cisco_backup"
    assert role_dir.exists(), "roles/cisco_backup directory missing"
    assert (role_dir / "tasks" / "main.yml").exists(), "roles/cisco_backup/tasks/main.yml missing"
    assert (role_dir / "defaults" / "main.yml").exists(), "roles/cisco_backup/defaults/main.yml missing"

def test_cisco_backup_playbook_structure():
    """Verify playbooks/backup_cisco.yml exists and defines correct hosts, pre_tasks, and role"""
    playbook_file = ROOT_DIR / "playbooks" / "backup_cisco.yml"
    assert playbook_file.exists(), "playbooks/backup_cisco.yml is missing"
    with open(playbook_file, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f)
    assert isinstance(data, list) and len(data) > 0
    play = data[0]
    assert play.get("hosts") == "cisco_switches"
    assert play.get("gather_facts") is False
    roles = [r if isinstance(r, str) else r.get("role") for r in play.get("roles", [])]
    assert "cisco_backup" in roles
    # Verify vars_files includes cisco_switches.yml
    vars_files = play.get("vars_files", [])
    assert any("cisco_switches.yml" in str(v) for v in vars_files)
    # Verify fail-fast pre_tasks
    pre_tasks = play.get("pre_tasks", [])
    assert len(pre_tasks) > 0, "pre_tasks missing in backup_cisco.yml"
    assert any("ansible_host" in str(t.get("ansible.builtin.assert", {}).get("that", [])) for t in pre_tasks)
    assert any("ansible_host != inventory_hostname" in str(t.get("ansible.builtin.assert", {}).get("that", [])) for t in pre_tasks)

def test_inventory_cisco_switches_example():
    """Verify cisco_switches group is documented in inventory hosts and group_vars"""
    inv_example = ROOT_DIR / "inventory" / "hosts.yml.example"
    with open(inv_example, "r", encoding="utf-8") as f:
        inv_data = yaml.safe_load(f)
    children = inv_data["all"].get("children", {})
    assert "cisco_switches" in children, "cisco_switches group missing from hosts.yml.example"

    cisco_vars_file = ROOT_DIR / "inventory" / "group_vars" / "cisco_switches.yml"
    assert cisco_vars_file.exists(), "group_vars/cisco_switches.yml is missing"
    with open(cisco_vars_file, "r", encoding="utf-8") as f:
        cisco_vars = yaml.safe_load(f)
    assert cisco_vars.get("ansible_network_os") in ["cisco.ios", "cisco.ios.ios"]
    assert cisco_vars.get("ansible_connection") == "network_cli"
    raw_content = cisco_vars_file.read_text(encoding="utf-8")
    assert "community.hashi_vault.hashi_vault" in raw_content
    assert "cisco_openbao_secret_prefix" in raw_content
    assert "cisco_openbao_namespace" in raw_content
    assert "secret=global/services" in raw_content

    # OpenBao 우선 로딩 및 인벤토리 폴백 검증
    assert "_cisco_sec.ansible_host" in raw_content
    assert "_cisco_sec.ansible_port" in raw_content
    assert "_cisco_sec.connection_type" in raw_content
    assert "_cisco_sec.ansible_user" in raw_content
    assert "_cisco_sec.ansible_password" in raw_content
    assert "_vault_token" in raw_content
    assert "vault_role_id" in raw_content
    assert "vault_secret_id" in raw_content
def test_cisco_backup_spec_ids_in_tasks_and_docs():
    """Verify CISCO spec IDs exist in tasks and docs"""
    tasks_file = ROOT_DIR / "roles" / "cisco_backup" / "tasks" / "main.yml"
    doc_file = ROOT_DIR / "docs" / "cisco_backup.md"
    assert tasks_file.exists()
    assert doc_file.exists()

    tasks_content = tasks_file.read_text(encoding="utf-8")
    doc_content = doc_file.read_text(encoding="utf-8")

    expected_specs = ["CISCO-001", "CISCO-002", "CISCO-003", "CISCO-004", "CISCO-005", "CISCO-006", "CISCO-007"]
    for spec in expected_specs:
        assert f"[{spec}]" in tasks_content, f"Spec [{spec}] missing in tasks"
        assert f"`{spec}`" in doc_content, f"Spec `{spec}` missing in docs"


def test_openssh_cli_collector_args_compatibility():
    """Verify OpenSSH arguments generated by collector do not fail OpenSSH option validation"""
    import subprocess
    import sys
    sys.path.insert(0, str(ROOT_DIR / "roles" / "cisco_backup" / "files"))
    from cisco_cli_collector import get_openssh_direct_args

    args = get_openssh_direct_args("127.0.0.1", 22, "dummy")
    # Validate with ssh -G dummy@127.0.0.1 or test invocation
    # ssh -G accepts the options and outputs the effective config, exiting 0 if valid
    val_cmd = ["ssh", "-G"] + args[2:]
    res = subprocess.run(val_cmd, capture_output=True, text=True)
    assert res.returncode == 0, f"OpenSSH rejected generated options: {res.stderr}"


def test_cisco_backup_openbao_unwrapping_logic():
    """Verify that backup_cisco.yml unwraps flat, nested, and array schemas with ansible_host, ip, user, port."""
    from jinja2 import Environment
    env = Environment()
    template_str = """
    {%- set _sw_raw = _openbao_direct_secret_resp.json.data.data if (_openbao_direct_secret_resp is defined and _openbao_direct_secret_resp.json is defined and _openbao_direct_secret_resp.json.data is defined and _openbao_direct_secret_resp.json.data.data is defined) else {} -%}
    {%- set _sw_unwrapped = (_sw_raw if _sw_raw is not mapping else (_sw_raw[inventory_hostname] if inventory_hostname in _sw_raw else ((_sw_raw.values() | first) if (_sw_raw | length > 0 and (_sw_raw.values() | first) is mapping) else _sw_raw))) -%}
    {%- set _sw_dict = (_sw_unwrapped | first) if (_sw_unwrapped is sequence and _sw_unwrapped is not string and _sw_unwrapped | length > 0 and (_sw_unwrapped | first) is mapping) else (_sw_unwrapped if _sw_unwrapped is mapping else {}) -%}
    {%- set _sw_resolved_host = _sw_dict.get('ansible_host', _sw_dict.get('ip', '')) -%}
    {%- set _sw_resolved_user = _sw_dict.get('ansible_user', _sw_dict.get('user', _sw_dict.get('username', ''))) -%}
    {%- set _sw_resolved_port = _sw_dict.get('ansible_port', _sw_dict.get('port', '')) -%}
    {{ {
      'ansible_host': _sw_resolved_host if (_sw_resolved_host | length > 0) else (ansible_host | default('', true)),
      'ansible_user': _sw_resolved_user if (_sw_resolved_user | length > 0) else (ansible_user | default('', true)),
      'ansible_port': ((_sw_resolved_port if (_sw_resolved_port | string | length > 0) else (ansible_port | default(22))) | int)
    } | tojson }}
    """
    tmpl = env.from_string(template_str)

    # 1. Flat schema
    r1 = yaml.safe_load(tmpl.render(
        _openbao_direct_secret_resp={'json': {'data': {'data': {'ansible_host': '211.210.44.182', 'ansible_user': 'ansible-backup', 'ansible_port': 22}}}},
        inventory_hostname='ns0278'
    ))
    assert r1['ansible_host'] == '211.210.44.182'
    assert r1['ansible_user'] == 'ansible-backup'
    assert r1['ansible_port'] == 22

    # 2. Nested dictionary under hostname with 'ip' and 'user'
    r2 = yaml.safe_load(tmpl.render(
        _openbao_direct_secret_resp={'json': {'data': {'data': {'ns0278': {'ip': '211.210.44.182', 'user': 'admin', 'port': 2222}}}}},
        inventory_hostname='ns0278'
    ))
    assert r2['ansible_host'] == '211.210.44.182'
    assert r2['ansible_user'] == 'admin'
    assert r2['ansible_port'] == 2222

    # 3. Array of dictionaries
    r3 = yaml.safe_load(tmpl.render(
        _openbao_direct_secret_resp={'json': {'data': {'data': [{'ansible_host': '218.54.219.82', 'username': 'telnet-user'}]}}},
        inventory_hostname='ns0065'
    ))
    assert r3['ansible_host'] == '218.54.219.82'
    assert r3['ansible_user'] == 'telnet-user'


